name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.10

    - name: Install dependencies
      run: uv sync --group dev

    - name: Run linting checks
      run: ./scripts/lint.sh --check

    - name: Run unit tests
      run: ./scripts/run-unit-tests.sh

    - name: Run integration tests
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: ./scripts/run-integration-tests.sh

    - name: Combine coverage reports
      run: ./scripts/combine-coverage.sh

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
